services:
  - type: web
    name: ai-backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y chromium-driver chromium-browser
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8000
